os:
  - linux

language: php

php:
  - '7.4'

env:
  - ILLUMINATE_VERSION=7.*

matrix:
  include:
    - php: 7.4
      env: ILLUMINATE_VERSION=7.*
    - php: 7.4
      env: ILLUMINATE_VERSION=6.*
    - php: 7.3
      env: ILLUMINATE_VERSION=7.*
    - php: 7.3
      env: ILLUMINATE_VERSION=6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*

before_install:
  - composer require "illuminate/database:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/config:${ILLUMINATE_VERSION}" --no-update

install: composer update --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit